version: '3.8'
services:  
  api:    
    build: ./    
    container_name: api_backend    
    ports:      
      - '4444:4444'    
    volumes:     
      - ./:/app      
      - ./app:/node_modules